### ISSUE TITLE
关于扩展

### ISSUE THREAD

**Issue by Topgt** [tlzzu/SoDiaoEditor.v2#29]
你好，原来百度ueditor提供的api是否还能使用？因为我有些功能要扩展，当使用原始api时出错。这是我的问题，还是您有意屏蔽百度ueditor提供的api。

**Comment by Topgt** [comment]
这是我自己的原因。我在实例化编辑器时穿错了问题。

**Comment by tlzzu** [comment]
原来的ueditor的功能还在，没有屏蔽原始api
