### ISSUE TITLE
我想找到 回车换行代码的位置，调试与不调试 情况不一样，自己定位不了，求作者帮忙给说一下 ！拜托了！

### ISSUE THREAD

**Issue by sj147258** [tlzzu/SoDiaoEditor.v2#48]
我想找到 回车换行代码的位置，调试与不调试 情况不一样，自己定位不了，求作者帮忙给说一下 ！拜托了！

**Comment by tlzzu** [comment]
你想要实现什么

**Comment by sj147258** [comment]
做的判断控制回车的内容，原始的回车加P标签没找到，回车事件找到了，就是一调试就不会车，不知道方法在哪里（无法定位，欲哭无泪啊！）！

**Comment by tlzzu** [comment]
可关注新版，即将发布
